### ISSUE TITLE
Trend of F1, R-value

### ISSUE THREAD

**Issue by ericwudayi** [felixkreuk/UnsupSeg#1]
Very amazing work and clean code! I have been trying to reproduce the result of your paper, and I have a question about the value of evaluation metrics during training. 

I use timit dataset for training and found that F1, R-value achieve the value as paper reported very quickly (in 5 epochs), and then just fluctuate around at certain value as shown below.
![image](https://user-images.githubusercontent.com/24611279/98262983-34ce0c00-1fc1-11eb-8a44-755e58d4101b.png)

Is this a normal situation?

**Comment by felixkreuk** [comment]
Hi @ericwudayi, thanks for the kind words! Indeed, for TIMIT the model converges very fast.
