### ISSUE TITLE
Configuration of Preprocessing Buckeye

### ISSUE THREAD

**Issue by ANLGBOY** [felixkreuk/UnsupSeg#7]
Hello @felixkreuk . Thanks for your nice work.

I'm wondering what configurations the authors have used for preprocessing the Buckeye dataset. (spkr, min_phonemes, max_phonemes)

**Comment by felixkreuk** [comment]
Hi,
Sure, `min_phonemes = 20` and `max_phonemes = 50` and `spkr` should be on.
